<a href="https://colab.research.google.com/github/maglys/DAT801-Assignment1-/blob/main/dat801_assignment1_magnus_rev2.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Kom i gang med DAT801-2021-konkurransen

***UNDER CONSTRUCTION***


Denne notebooken beskriver hvordan du kan:
1. Laste inn data: vi bruker Pandas til å laste inn trenings- og test-data
2. Undersøke features: vi undersøker et par features via statistikk og enkle plots.
3. Submitte dine prediksjoner for scoring (og plassering på leaderboard): etter at du har laget en modell og produsert prediksjoner på testdata så må du samle disse i en fil som Kaggle kan bruke til scoring. 

_Hvis du vil bruke denne notebooken som utgangspunkt for ditt eget arbeid kan du trykke "Fork"_

Du kan eventuelt bruke Google Colab eller din egen maskin. For å bruke Colab, (i) last ned notebooken på din egen maskin, (ii) gå til https://colab.research.google.com, logg inn, og last opp notebooken. 

# Setup

In [1]:
%matplotlib inline
import numpy as np, pandas as pd, seaborn as sns, matplotlib.pyplot as plt
from pathlib import Path

# Last inn data

## Hvis du arbeider lokalt

Last ned data via Data-menyen på konkurransens hjemmeside.

## Hvis du bruker Colab

Kjør følgende celle:

In [2]:
train = pd.read_csv('https://raw.githubusercontent.com/alu042/DAT801/master/KaggleInClass/train.csv')
test = pd.read_csv('https://raw.githubusercontent.com/alu042/DAT801/master/KaggleInClass/test.csv')
sampleSubmission = pd.read_csv('https://raw.githubusercontent.com/alu042/DAT801/master/KaggleInClass/sample_submission.csv')

## Hvis du bruker Kaggle

In [3]:
#DATA = Path('../input/dat801-2021-assignment1')
#list(DATA.iterdir())

In [4]:
#train = pd.read_csv(DATA/'train.csv')
#test = pd.read_csv(DATA/'test.csv')
#sampleSubmission = pd.read_csv(DATA/'sample_submission.csv')

# Ta en titt på data

In [5]:
train.head()

id   f_0  f_1  f_2  f_3  f_4  ...  f_70  f_71  f_72  f_73  f_74  target
0  161363   1.0  0.0  0.0  0.0  1.0  ...   0.0   NaN   NaN   0.0   0.0       6
1   78028  16.0  0.0  1.0  1.0  6.0  ...   0.0   0.0   2.0   1.0   1.0       7
2   35324   0.0  3.0  0.0  1.0  1.0  ...   1.0   0.0   1.0   0.0   0.0       5
3   67966   0.0  0.0  0.0  0.0  0.0  ...   0.0   0.0   0.0   0.0   0.0       1
4  110279   3.0  0.0  0.0  2.0  0.0  ...   4.0   0.0   0.0   0.0   1.0       5

[5 rows x 77 columns]

In [6]:
train.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 150000 entries, 0 to 149999
Data columns (total 77 columns):
 #   Column  Non-Null Count   Dtype  
---  ------  --------------   -----  
 0   id      150000 non-null  int64  
 1   f_0     147000 non-null  float64
 2   f_1     148500 non-null  float64
 3   f_2     149250 non-null  float64
 4   f_3     149250 non-null  float64
 5   f_4     148500 non-null  float64
 6   f_5     149250 non-null  float64
 7   f_6     147000 non-null  float64
 8   f_7     147000 non-null  float64
 9   f_8     149250 non-null  float64
 10  f_9     148500 non-null  float64
 11  f_10    148500 non-null  float64
 12  f_11    148500 non-null  float64
 13  f_12    148500 non-null  float64
 14  f_13    148500 non-null  float64
 15  f_14    149250 non-null  float64
 16  f_15    147000 non-null  float64
 17  f_16    149250 non-null  float64
 18  f_17    148500 non-null  float64
 19  f_18    148500 non-null  float64
 20  f_19    148500 non-null  float64
 21  f_20    14

Vi ser at det er 150.000 instanser i treningsdata. Det mangler noen verdier i hver av features (som er noe en må takle ved hjelp av imputering eller lignende).

In [7]:
test.head()

id  f_0  f_1  f_2  f_3  f_4  ...  f_69  f_70  f_71  f_72  f_73  f_74
0  105982    0    0   10    0    0  ...     1     0     0     0     0     0
1  137351    0    0    0    0    0  ...     6     0     0     0     0     0
2  151824    0    0    0    0    0  ...     0     0     0     0     0     0
3  152873    1    2    0    1    2  ...     0     1     1     0     0     0
4   61900    3    0    0    0    0  ...     3     0     0     0     0     0

[5 rows x 76 columns]

In [8]:
test.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 50000 entries, 0 to 49999
Data columns (total 76 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   id      50000 non-null  int64
 1   f_0     50000 non-null  int64
 2   f_1     50000 non-null  int64
 3   f_2     50000 non-null  int64
 4   f_3     50000 non-null  int64
 5   f_4     50000 non-null  int64
 6   f_5     50000 non-null  int64
 7   f_6     50000 non-null  int64
 8   f_7     50000 non-null  int64
 9   f_8     50000 non-null  int64
 10  f_9     50000 non-null  int64
 11  f_10    50000 non-null  int64
 12  f_11    50000 non-null  int64
 13  f_12    50000 non-null  int64
 14  f_13    50000 non-null  int64
 15  f_14    50000 non-null  int64
 16  f_15    50000 non-null  int64
 17  f_16    50000 non-null  int64
 18  f_17    50000 non-null  int64
 19  f_18    50000 non-null  int64
 20  f_19    50000 non-null  int64
 21  f_20    50000 non-null  int64
 22  f_21    50000 non-null  int64
 23  f_22    500

Det er 50.000 test-instanser, og det ser ikke ut til å mangle noen features. 

# Utforsk data, preprosesser data, utforsk modeller ("model selection"), prediker & evaluer

Jeg overlater disse delene til dere. Du bør utforske features via statistikk og plots, forsøke å avdekke sammenhenger mellom features og mellom features og labels ved å undersøke korrelasjoner og lignende, og gjerne forsøke å konstruere nye features ved å kombinere eksisterende. Før du kan trene modeller må du sørge for at data er på en egnet form. Du må blant annet finne ut hvordan du best kan takle manglende verdier ("missing values"). Husk å designe et grundig evalueringsoppsett som du kan bruke underveis i utforskingen av modeller. Kryss-validering er naturlig. Bør du kanskje vurdere stratifisert splitting i trening- og validerings-data? Hva med ensembling av flere modeller?

In [9]:
sampleSubmission.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 50000 entries, 0 to 49999
Data columns (total 2 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   id      50000 non-null  int64
 1   target  50000 non-null  int64
dtypes: int64(2)
memory usage: 781.4 KB


#Setup

In [10]:
from sklearn.model_selection import train_test_split, cross_val_score
from sklearn.preprocessing import StandardScaler, MinMaxScaler
from sklearn.metrics import accuracy_score, precision_score, recall_score, f1_score
from sklearn.preprocessing import StandardScaler
from sklearn.impute import SimpleImputer
import scipy.sparse as sp
from sklearn.ensemble import RandomForestClassifier
from sklearn.impute import KNNImputer
from sklearn.metrics import confusion_matrix

#Splitt i trening og valideringsdata

## Splitt i X og y

Deler opp data i X (features) og y (target).

In [11]:
X = train.drop('target', axis=1)
X = X.drop('id', axis=1)
y = train['target']
X.head()

f_0  f_1  f_2  f_3  f_4  f_5  f_6  ...  f_68  f_69  f_70  f_71  f_72  f_73  f_74
0   1.0  0.0  0.0  0.0  1.0  0.0  0.0  ...   0.0   0.0   0.0   NaN   NaN   0.0   0.0
1  16.0  0.0  1.0  1.0  6.0  2.0  2.0  ...   3.0   0.0   0.0   0.0   2.0   1.0   1.0
2   0.0  3.0  0.0  1.0  1.0  0.0  0.0  ...   0.0   1.0   1.0   0.0   1.0   0.0   0.0
3   0.0  0.0  0.0  0.0  0.0  1.0  0.0  ...   0.0   2.0   0.0   0.0   0.0   0.0   0.0
4   3.0  0.0  0.0  2.0  0.0  0.0  0.0  ...   1.0   5.0   4.0   0.0   0.0   0.0   1.0

[5 rows x 75 columns]

In [12]:
#y.head()
#X.shape
#type(y)
X.describe()
#X.info()

f_0            f_1  ...           f_73           f_74
count  147000.000000  148500.000000  ...  148500.000000  148500.000000
mean        0.970327       1.173293  ...       2.938626       0.628350
std         3.910666       4.003482  ...      10.778694       3.903292
min         0.000000       0.000000  ...       0.000000       0.000000
25%         0.000000       0.000000  ...       0.000000       0.000000
50%         0.000000       0.000000  ...       0.000000       0.000000
75%         1.000000       1.000000  ...       1.000000       0.000000
max        61.000000      51.000000  ...     130.000000      52.000000

[8 rows x 75 columns]

In [13]:
# Split into training and test sets
X_train, X_val, y_train, y_val = train_test_split(X, y, test_size=0.25, random_state=42)

#Uforsk data

In [14]:
#pd.plotting.scatter_matrix(iris_df[features], c=iris_df['label'], figsize=(15,15), marker='o', s=60)
#plt.show()

##Feature selection

In [15]:
#Valg av egenskaper

In [16]:
import matplotlib.pyplot as plt
import seaborn as sb
# sb.heatmap(df.corr(), square=True, cmap='RdYlGn')

#Preprosessering

## Fylle inn manglende verdier

Univariate vs. Multivariate Imputation

### Dropp nullverdier

In [17]:
# Gjort på toppen
# train = train.dropna() # dropper all data med NaN
train.shape

(150000, 77)

###SimpleImputer

In [18]:

imp = SimpleImputer(missing_values=np.nan, strategy='mean')
imp.fit(X_train)
SimpleImputer()
X_train = pd.DataFrame(imp.transform(X_train))
X_val = pd.DataFrame(imp.transform(X_val))


In [19]:
X_train.describe()


0              1   ...             73             74
count  112500.000000  112500.000000  ...  112500.000000  112500.000000
mean        0.970430       1.167047  ...       2.949127       0.624540
std         3.849702       3.980731  ...      10.770300       3.876789
min         0.000000       0.000000  ...       0.000000       0.000000
25%         0.000000       0.000000  ...       0.000000       0.000000
50%         0.000000       0.000000  ...       0.000000       0.000000
75%         1.000000       1.000000  ...       1.000000       0.000000
max        61.000000      51.000000  ...     130.000000      52.000000

[8 rows x 75 columns]

### KNNImputer

In [20]:
#nan = np.nan
#imputer = KNNImputer(n_neighbors=2, weights="uniform")
#imputer.fit_transform(train)

## Skaler data

In [21]:
"""
from sklearn.preprocessing import StandardScaler, MinMaxScaler
scaler = StandardScaler()
#scaler = MinMaxScaler()
scaler.fit(X_train)
X_train = scaler.transform(X_train)
X_val = scaler.transform(X_val)
"""



'\nfrom sklearn.preprocessing import StandardScaler, MinMaxScaler\nscaler = StandardScaler()\n#scaler = MinMaxScaler()\nscaler.fit(X_train)\nX_train = scaler.transform(X_train)\nX_val = scaler.transform(X_val)\n'

# Valg av ML-modell

## Random Forest

In [22]:

# Import and train a machine learning model
rf = RandomForestClassifier(random_state=42, max_depth=10, n_estimators=300)
rf.fit(X_train, y_train)






RandomForestClassifier(bootstrap=True, ccp_alpha=0.0, class_weight=None,
                       criterion='gini', max_depth=10, max_features='auto',
                       max_leaf_nodes=None, max_samples=None,
                       min_impurity_decrease=0.0, min_impurity_split=None,
                       min_samples_leaf=1, min_samples_split=2,
                       min_weight_fraction_leaf=0.0, n_estimators=300,
                       n_jobs=None, oob_score=False, random_state=42, verbose=0,
                       warm_start=False)

## Kryssvalidering

In [23]:
"""
cv_scores = cross_val_score(rf, X_train, y_train, cv=5, scoring='accuracy', n_jobs=-1)

print(cv_scores)
print(cv_scores.mean())
"""

"\ncv_scores = cross_val_score(rf, X_train, y_train, cv=5, scoring='accuracy', n_jobs=-1)\n\nprint(cv_scores)\nprint(cv_scores.mean())\n"

In [24]:
y_val.head()
type(y_val) #pandas.core.series.Series
# print(y_val)

pandas.core.series.Series

### Prediker & evaluer

In [25]:
# Predict on the test data
y_pred = rf.predict(X_val)
#print(type(y_pred)) #numpy.ndarray
#y_test1=(y_test.to_numpy()) #Konvertering til numpy
#np.array(y_val)
# y = y.reshape(-1, 1)
# X = X.reshape(-1, 1)

# Evaluate the model
accuracy_score(y_val, y_pred)
"""for å legge til index
food= food.reset_index()
food= food.set_index('id')
print(food)
"""

"for å legge til index\nfood= food.reset_index()\nfood= food.set_index('id')\nprint(food)\n"

### Confusion matrix

In [26]:
# Print the confusion matrix
print(confusion_matrix(y_val, y_pred))
print()
"""
cv_scores_new = cross_val_score(sgd_clf, X_train_scale, y_train, cv=5, 
                            scoring='accuracy', n_jobs=-1)
print('Cross val score: ' + str(cv_scores_new))
print('CV score mean: ' + str(cv_scores_new.mean()))
"""
print()
print('Accuracy: ' + str(accuracy_score(y_val, y_pred)))



[[   0  378    0    0    0  454    0  886    0]
 [   0 2105    0    0    0  991    0 1462    0]
 [   0  997    0    0    0  671    0 1124    0]
 [   0  203    0    0    0  242    0  462    0]
 [   0  112    0    0    0  156    0  318    0]
 [   0  814    0    0    0 4939    0 4150    0]
 [   0  266    0    0    0  648    0 1794    0]
 [   0  653    0    0    0 2431    0 6463    0]
 [   0 1005    0    0    0 1288    0 2488    0]]


Accuracy: 0.36018666666666665


## SGDClassifier

In [27]:

"""
# Evaluate the model
accuracy_score(y_test, y_pred)

cv_scores = cross_val_score(sgd_clf, X_train, y_train, cv=5, 
                            scoring='accuracy', n_jobs=-1)

# Create an instance of the StandardScaler
#scaler = StandardScaler()
scaler = MinMaxScaler()

# Using Scaler on the training data
scaler.fit(X_train)

# Transform the training and test data:
X_train_scale = scaler.transform(X_train)
X_test_scale = scaler.transform(X_test)

# Create and train an SGDClassifier
sgd_clf_scale = SGDClassifier()
sgd_clf_scale.fit(X_train_scale, y_train)

# Compute the cross-validation predictions on the training set
y_test1, y_pred = cross_val_predict(sgd_clf, X_train_scale, y_train, cv=5)

"""

"\n# Evaluate the model\naccuracy_score(y_test, y_pred)\n\ncv_scores = cross_val_score(sgd_clf, X_train, y_train, cv=5, \n                            scoring='accuracy', n_jobs=-1)\n\n# Create an instance of the StandardScaler\n#scaler = StandardScaler()\nscaler = MinMaxScaler()\n\n# Using Scaler on the training data\nscaler.fit(X_train)\n\n# Transform the training and test data:\nX_train_scale = scaler.transform(X_train)\nX_test_scale = scaler.transform(X_test)\n\n# Create and train an SGDClassifier\nsgd_clf_scale = SGDClassifier()\nsgd_clf_scale.fit(X_train_scale, y_train)\n\n# Compute the cross-validation predictions on the training set\ny_test1, y_pred = cross_val_predict(sgd_clf, X_train_scale, y_train, cv=5)\n\n"

# Submission

Etter at du har trent din modell / dine modeller og produsert prediksjoner på test-data, så må du lage en CSV-fil på korrekt form som kan scores av Kaggle. Den skal ha samme form som `sample_submission.csv`:

In [28]:
sampleSubmission.head()

id  target
0  105982       7
1  137351       7
2  151824       7
3  152873       7
4   61900       7

Her er en fremgangsmåte:

Vi trenger først en vektor med tilfeldige prediksjoner:

In [29]:
#target = np.random.choice(range(9), size=len(test))
#target

In [30]:
test2 = test.drop('id', axis=1)
test.head()

id  f_0  f_1  f_2  f_3  f_4  ...  f_69  f_70  f_71  f_72  f_73  f_74
0  105982    0    0   10    0    0  ...     1     0     0     0     0     0
1  137351    0    0    0    0    0  ...     6     0     0     0     0     0
2  151824    0    0    0    0    0  ...     0     0     0     0     0     0
3  152873    1    2    0    1    2  ...     0     1     1     0     0     0
4   61900    3    0    0    0    0  ...     3     0     0     0     0     0

[5 rows x 76 columns]

In [31]:
# Predict on the test data
target = rf.predict(test2)
target


array([5, 5, 5, ..., 7, 5, 7])

Vi kan så bygge en dataframe via en Python dictionary med nøkler ("keys") 'id' og 'target':

In [32]:
submission = pd.DataFrame({'id': test['id'], 'target': target})

In [33]:
submission.head()

id  target
0  105982       5
1  137351       5
2  151824       5
3  152873       7
4   61900       1

Denne kan lagres som en CSV vi kan laste opp på Kaggle for scoring:

In [34]:
submission.to_csv('submission_mag1.csv', index=False)